services:
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/static:ro
    depends_on:
      - app1
      - app2

  app1:
    build:
      context: ./app
    ports:
      - 8000:8000
    restart: unless-stopped
    
  app2:
    build:
      context: ./app
    ports:
      - 8001:8000
    restart: unless-stopped